package org.sample

// removed 'case' keyword to skip all autogenerated method, 
// they obscure coverage too much
class Person(val first: String, val last: String, val age: Int) {
  def valid: Boolean = age > 18

  override def toString() = 
    this.first + " " + this.last + " " + this.age
}
